### ISSUE TITLE
Cannot get spaces, spaceKey values issue

### ISSUE THREAD

**Issue by emulienfou** [MrRefactoring/confluence.js#14]
Hi there, trying to get multiple spaces from Confluence however it seems there is an issue.

Here is the code that I use to get my spaces:
```js
await client.space.getSpaces({ spaceKey: ['KEY1', 'KEY2'] })
```

The documentation said:
> Returns information about a number of spaces.
Example request URI(s):
http://example.com/rest/api/space?spaceKey=TST&spaceKey=ds

However the generated URL is: `https://example.atlassian.net/wiki/rest/api/space?spaceKey=KEY1,KEY2`
Instead of: `https://example.atlassian.net/wiki/rest/api/space?spaceKey=KEY1&spaceKey=KEY2`

**Comment by MrRefactoring** [comment]
Hi @emulienfou. Thank you for report. Yeah it's definitely a bug

**Comment by MrRefactoring** [comment]
Issue still here :(

**Comment by MrRefactoring** [comment]
@emulienfou please check v1.3.1

**Comment by emulienfou** [comment]
@MrRefactoring v1.3.1 fix the issue, I was able to make it work with single and multiple `spaceKey` values.
Thanks for the quick fix

**Comment by MrRefactoring** [comment]
Thanks for you contribution!
