### ISSUE TITLE
Attachments download

### ISSUE THREAD

**Issue by hypery2k** [MrRefactoring/confluence.js#15]
I tried to use the downloadAttachement feature, but the encoding seems incorrect:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/979121/145059941-b447e43a-cbf8-4ad3-a46d-c009e646e057.png">

`�PNG...` --> should begin with  `<89>PNG...`

Any ideas?

**Comment by MrRefactoring** [comment]
Hi @hypery2k. I will play with axios encoding may it help :)

**Comment by hypery2k** [comment]
thanks for the fast response, I think a customer `OnResponseHandler ` ( see https://github.com/MrRefactoring/confluence.js/blob/master/src/clients/baseClient.ts#L137 could help)

I could be added here: https://github.com/MrRefactoring/confluence.js/blob/master/src/api/contentAttachments.ts#L375

**Comment by MrRefactoring** [comment]
Hi @hypery2k. I fixed it. Now you can just writeFile when getting a response (return type is ArrayBuffer)

**Comment by hypery2k** [comment]
thanks, works now.
