### ISSUE TITLE
Adding attachments complains about mediatype

### ISSUE THREAD

**Issue by tester22** [MrRefactoring/confluence.js#23]
Hi,

I am getting 415 when trying to add attachments using the method bellow. Do you have any unit tests or examples on how this should be used?

https://github.com/MrRefactoring/confluence.js/blob/738dc5688d37e97073c5c62d0394ddc57ccaa402/src/api/contentAttachments.ts#L82

**Comment by MrRefactoring** [comment]
Hi @tester22! Sorry for the late response, could you please provide an example of how you use this method?

**Comment by MrRefactoring** [comment]
So I took a look and got you :)

Yeah, looks like it's wouldn’t work

**Comment by MrRefactoring** [comment]
Fixed in `v1.5.0`. If you still have problems with adding attachments check `e2e.test.ts` file

**Comment by tester22** [comment]
Thanks!

It works great now!
