### ISSUE TITLE
how to get an article on my wiki with this js

### ISSUE THREAD

**Issue by xiewenchong** [MrRefactoring/confluence.js#26]
I'm a novice. I want to get an article on my wiki. What should I do

**Comment by xiewenchong** [comment]
Is there a complete JS example for reference, which can be run directly

**Comment by MrRefactoring** [comment]
https://codesandbox.io/s/confluence-js-article-creation-example-cgt468?file=/index.ts

**Comment by MrRefactoring** [comment]
1. Example of URL: https://xxx.atlassian.net/
2. Email it is your email
3. How to issue new access token you can read here: https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/
4. For getting article use `client.content.getContent` method

**Comment by xiewenchong** [comment]
I want to get my personal space, but I don't know the parameters when I query the space, so I can't filter the query. What should I do

**Comment by xiewenchong** [comment]
I want to get my personal space, but I don't know the parameters when I query the space, so I can't filter the query. What should I do
![image](https://user-images.githubusercontent.com/36987413/178423334-f12ec8c0-e38a-410c-862e-d400f41e1912.png)
![image](https://user-images.githubusercontent.com/36987413/178423351-8b4ea31d-c8cd-40c6-afae-a92e1b9819b5.png)

**Comment by MrRefactoring** [comment]
Hi @xiewenchong! Try to use `space.getSpaces()` method for getting all available spaces

**Comment by MrRefactoring** [comment]
Hi @xiewenchong! Any progress?
