### ISSUE TITLE
[ServerClient] Creating and Updating attachments returns 415 

### ISSUE THREAD

**Issue by ggarcia24** [MrRefactoring/confluence.js#27]
Hello!

First of all thanks for this awesome lib! kudos to you 🥳 

I think this is related to #23 , according to the [server documentation][https://docs.atlassian.com/ConfluenceServer/rest/7.18.3/#content/{id}/child/attachment-updateData] in order to update an attachment data the `content-type` header of the request needs to be `multipart/form-data` but it's currently being set to `application/json`

Please let me know if you need code examples and files, I can provide those, I'm reading a bit the code, trying to understand things, I will also try to submit a fix for this later🤞 

Best regards
Gonzalo G

**Comment by MrRefactoring** [comment]
Hi @ggarcia24! Thank you! I will wait your PR :)

**Comment by MrRefactoring** [comment]
Released in v1.5.2. Thanks for your work
