### ISSUE TITLE
'urlSuffix' is better to be a configuration option.

### ISSUE THREAD

**Issue by xucongli1989** [MrRefactoring/confluence.js#35]
# Description
I think someone's Conluence home page is not start with `/wiki/`. Thanks!

# Code
https://github.com/MrRefactoring/confluence.js/blob/ac097f51d807284ed08ab8619a4b8208bdb548e0/src/clients/baseClient.ts#L14

**Comment by MrRefactoring** [comment]
Hello @xucongli1989! Thanks for mentioning it. Needs to improve it

**Comment by tschannik** [comment]
Hi, 

I'm trying to use the library but my confluence instance doesn't use the wiki suffix. Is there a way or configuration currently usable to get around that?

**Comment by xucongli1989** [comment]
@tschannik , you can try this:

``` javascript 
const client = new ConfluenceClient({...})
client.urlSuffix = "/rest/"
```

**Comment by tschannik** [comment]
@xucongli1989 

That works :) would be also nice if it could be configurable in the constructor. I could open a PR if i have time later 👍

**Comment by tschannik** [comment]
#41

**Comment by MrRefactoring** [comment]
Will be added with V2 API
