### ISSUE TITLE
Convert Dash-Cased Parameters to CamelCase in `getBlogPostById`

### ISSUE THREAD

**Issue by MrRefactoring** [MrRefactoring/confluence.js#58]
In the [getBlogPostById](https://github.com/MrRefactoring/confluence.js/blob/feature/v2-api/src/version2/blogPost.ts#L105C46-L105C46) function, parameters with a dash (-) are used. The proposal is to replace these `dash-cased` parameters with `camelCase`.

#### The function currently looks like this:

```typescript
async getBlogPostById<T = Models.BlogPost>(
    parameters: Parameters.GetBlogPostById,
    callback?: Callback<T>,
): Promise<void | T> {
    const config: RequestConfig = {
      url: `/blogposts/${parameters.id}`,
      method: 'GET',
      params: {
        'body-format': parameters['body-format'],
        'get-draft': parameters['get-draft'],
        version: parameters.version,
        'serialize-ids-as-strings': true,
      },
    };

    return this.client.sendRequest(config, callback);
} 
```

#### Expected function look:

```typescript
async getBlogPostById<T = Models.BlogPost>(
    parameters: Parameters.GetBlogPostById,
    callback?: Callback<T>,
): Promise<void | T> {
    const config: RequestConfig = {
      url: `/blogposts/${parameters.id}`,
      method: 'GET',
      params: {
        'body-format': parameters.bodyFormat,
        'get-draft': parameters.getDraft,
        version: parameters.version,
        'serialize-ids-as-strings': true,
      },
    };

    return this.client.sendRequest(config, callback);
} 
```

**Comment by augustus-thomas** [comment]
I am interested in helping with this project and saw that there are a number of files you need refactored under "good first issue"

How do you suggest I write tests for the files if I change them and PR? Because they are local params and don't affect the context they run in do they need retesting?

**Comment by MrRefactoring** [comment]
Hi @augustus-thomas! Thank you for your interest! Actually, tests are not required here, only change the naming of some parameters and that's it
